### ISSUE TITLE
You seem to be committing directly on the develop branch. Use pull-based instead

### ISSUE THREAD

**Issue by jrfaller** [MarcBrout/HQSE_2#5]
That could have helped you to spot the build folder being committed :)

**Comment by thomaslmbrt** [comment]
Hi @jrfaller !

We have encountered a problem about our repository and branches configuration.

As you know, we try to keep our project as clean as possible, so we have already fixed that one. It is not going to happen for the next time.

Thanks for your comprehension.

Have a nice day!

The HQSE_2 team.
